# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:

      - run:
          name: Creating soltuion folder
          command: |
            mkdir /tmp/artifacts

      - checkout

      # Download and cache dependencies

      - run: npm install
      
      - run: sudo npm link gulp
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      # run gulp
      - run: echo "run gulp tasks"
      - run: gulp clean
      - run: gulp bundle
      - run: gulp package-solution --ship
      - store_artifacts:
          path: ./sharepoint/solution/spfx-circle-ci.sppkg

      # run tests!
      - run: npm test
